export enum ActionTypes {
  CREATE_NOTE = "CREATE_NOTE",
  UPDATE_NOTE = "UPDATE_NOTE",
  DELETE_NOTE = "DELETE_NOTE",
  GET_NOTE_BY_ID = "GET_NOTE_BY_ID",
  GET_ALL_NOTES = "GET_ALL_NOTES",
  SET_NOTE = "SET_NOTE",
  UPDATE_NOTE_DATA = "UPDATE_NOTE_DATA",
}
